{{- if and .Values.rag.openAI.createSecret .Values.rag.openAI.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag.fullname" . }}-openai
  labels:
    {{- include "rag.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.rag.openAI.apiKey | b64enc }}
  {{- if .Values.rag.openAI.baseURL }}
  baseURL: {{ .Values.rag.openAI.baseURL | b64enc }}
  {{- end }}
{{- end }}

